configMapGenerator:
- files:
  - application.yml
  name: 82265576-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: "82265576"
images:
- name: ceappacr.azurecr.io/82265576
  newTag: "202410290650"
- name: cepgstapacr.azurecr.io/82265576
  newTag: "202410280724"
